---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk

inputs:
  - name: pcfdemo

run:
  path: pcfdemo/ci/tasks/integration.sh
  args: [
    --input-dir, pcfdemo
  ]
