---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/cf-java-client

inputs:
  - name: pcfdemo

run:
  path: pcfdemo/ci/tasks/integration.sh
  args: [
    --input-dir, pcfdemo
  ]
