---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/cf-java-client

inputs:
  - name: pcfdemo
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-final

run:
  path: pcfdemo/ci/tasks/prepare-final.sh
  args: [
    "--input-dir", "candidate-release",
    "--output-dir", "prepare-final",
    "--version-file", "version/number"
  ]
